const data = [
        {
            id:"1", 
            marca:"Accer", 
            nombre: "Accer Aspire 5", 
            procesador:"Ryzen 3 4300u 3.7 GHz", 
            memoria: "4GB", 
            almacenamiento:"SSD 128 GB NVMe", 
            pantalla:"15,6",
            tipo:"Gamer", 
            precio:"85000",
            desc: "Para obtener un mejor rendimiento, la Aspire 5 utiliza los procesadores AMD más recientes, 8 GB DDR 4 de memoria y brinda energía suficiente para que pueda trabajar durante su día laboral. Trabaje, juegue o relájese; hágalo todo con una gran productividad. La pantalla Full HD es capaz de ofrecer imágenes y videos impresionantes, mientras el borde delgado ofrece más espacio de visualización. Para proteger la vista de los usuarios contra la dañina luz azul, incluye Acer BlueLightShield. Con un disco de 256GB SSD, los usuarios tienen una gran capacidad de almacenamiento y velocidad para todos sus archivos multimedia y de trabajo, entre otros. El práctico diseño se redujo para ofrecerles a los usuarios un dispositivo que se puede transportar fácilmente y que además incluye una bisagra ergonómica que permite un flujo de aire adicional desde la parte inferior de la laptop. ", 
            img:"https://http2.mlstatic.com/D_NQ_NP_736183-MLA49127741114_022022-V.webp",
            stock: "7",
            categoria: "1",  
        },
        {
            id:"2", 
            marca:"Asus", 
            nombre: "Asus TUF", 
            procesador:"AMD Ryzen 7  2.3GHz", 
            memoria: "16GB", 
            almacenamiento:"512GB SSD", 
            pantalla:"15,6",
            tipo:"Gamer", 
            precio:"175000",
            desc: "Armado con la fuerza para abordar cualquier situación, el TUF Gaming A15 ofrece un rendimiento confiable para juegos, transmisión y todo lo demás. Una CPU AMD Ryzen ™ 7 ágil de 8 núcleos puede activar hasta 16 subprocesos para realizar múltiples tareas. Junto con una GPU GeForce RTX ™ 3060, puede generar velocidades de cuadro altas y confiables en una amplia gama de juegos populares.",  
            img: "https://http2.mlstatic.com/D_NQ_NP_889449-MLA47446389763_092021-V.webp",
            stock: "10",
            categoria: "1",   
        },
        {
            id:"3", 
            marca:"HP", 
            nombre: "HP", 
            procesador:"MediaTek MT8183 2.0GHz", 
            memoria: "4GB", 
            almacenamiento:"SSD 128 GB NVMe", 
            pantalla:"11,6",
            tipo:"", 
            precio:"52000",
            desc: "Ligero y lo suficientemente compacto como para llevarlo a cualquier lugar sin la toma de corriente. Una batería de larga duración te permite desconectarte del cable mientras te mantengas conectado con el mundo. Configuración detallada: 4 GB de RAM sustancial de ancho de banda alto para ejecutar sin problemas tus juegos y aplicaciones de edición de fotos y vídeo, así como múltiples programas y pestañas de navegador, todo a la vez. Un SSD de 32 GB basado en flash no tiene partes móviles, lo que resulta en tiempos de arranque más rápidos y acceso a datos, sin ruido, y reducción de la producción de calor y consumo de energía en la batería.",  
            img: "https://http2.mlstatic.com/D_NQ_NP_878279-MLA46926180427_072021-V.webp",
            stock: "3",
            categoria: "1",  
        },
        {
            id:"4", 
            marca:"Asus", 
            nombre: "Asus", 
            procesador:"Celeron 2.4Ghz", 
            memoria: "4GB", 
            almacenamiento:"32GB", 
            pantalla:"15,6", 
            tipo:"", 
            precio:"63999", 
            desc:"Disfrutá de la perfecta combinación de rendimiento y diseño con esta notebook Asus Ultra Thin L510MA. Encontrarás en ella una excelente herramienta para tus trabajos de todos los días y para tus momentos de entretenimiento. Aprovechá la experiencia extraordinaria que la marca tiene para ofrecerte y optimizá la calidad de tus imágenes y videos. Con su procesador Intel Celeron de 2 núcleos, lograrás el desempeño que necesitás para navegar y trabajar. Podrás usar los programas más esenciales, llevar a cabo tus tareas y organizar tu vida diaria. El disco sólido de 128 GB hace que el equipo funcione a gran velocidad y por lo tanto te brinda mayor agilidad para operar con diversos programas. Su placa de video Intel UHD Graphics 600 convierte a este dispositivo en una gran herramienta de trabajo para cualquier profesional del diseño. Te permitirá lograr una gran performance en todos tus juegos y en otras tareas cotidianas que impliquen procesamiento gráfico.",
            img:"https://http2.mlstatic.com/D_NQ_NP_732764-MLA48048741966_102021-V.webp",
            stock: "12",
            categoria: "1",  
        },
        {
            id:"5", 
            marca:"HP", 
            nombre: "HP Pavilion", 
            procesador:"AMD Ryzen™ 7 4800H 2,9 GHz", 
            memoria: "8GB", 
            almacenamiento:"512GB", 
            pantalla:"15,6",
            tipo:"Gamer", 
            precio:"165000",
            desc: "Una laptop compacta que facilita el trabajo mientras viajas gracias a que cuenta con un panel táctil de precisión, al mismo tiempo que la larga duración de la batería y la tecnología HP Fast Charge te permiten seguir en movimiento. Una computadora portátil con un rendimiento impresionante. Su revolucionaria arquitectura con una impresionante batería de larga duración incorpora prestaciones de procesamiento múltiple y una tarjeta gráfica Vega que permite resolver las tareas multimedia más exigentes.",  
            img:"https://http2.mlstatic.com/D_NQ_NP_668255-MLA49520367727_032022-V.webp",
            stock: "5",
            categoria: "1",  
        },
        {
            id:"6", 
            marca:"Asus", 
            nombre: "Asus Tuf Dash", 
            procesador:"Intel Core i7 4 nucleos", 
            memoria: "8GB", 
            almacenamiento:"512GB", 
            pantalla:"15,6",
            tipo:"Gamer", 
            precio:"249500",
            desc: "El nuevo TUF Dash F15 pone los potentes juegos de Windows 10 Pro en un chasis súper delgado. La última CPU Intel Core i7-11370H de 11.ª generación y la GPU GeForce RTX 3050 Ti hacen que los juegos sean fluidos hasta en una pantalla ultrarrápida de 144Hz. Incluso con un grosor de 19.9 mm, este chasis TUF cumple con los rigurosos estándares de durabilidad MIL-STD y resiste los golpes y los golpes diarios. Hasta 16.6 horas de batería le permite realizar más tareas múltiples en una computadora portátil lo suficientemente liviana como para llevarla a la acción en cualquier lugar.",  
            img:"https://http2.mlstatic.com/D_NQ_NP_905083-MLA47892225167_102021-V.webp",
            stock: "4",
            categoria: "1", 
        },
        {
            id:"7", 
            marca:"Logitech", 
            nombre: "Logitech G Series G305", 
            tipo:"Gamer Inalámbrico", 
            precio:"3990",
            desc: "Rapidez y confiabilidad de los botones, con sus 6 botones podrás tener mayor control e independencia para ejecutar. Plug And Play, solo debés colocar el receptor en un puerto USB de la computadora y ya podés empezar a usarlo. No hace falta emparejar el mouse ni descargar software para utilizarlo. Navegá rápidamente por documentos y páginas web gracias su diseño ultra delgado, ergonómico, liviano y conveniente para llevar a donde quieras o viajar.", 
            img:"https://http2.mlstatic.com/D_NQ_NP_816875-MLA44091562002_112020-V.webp",
            stock: "7",
            categoria: "2", 
        },
        {
            id:"8", 
            marca:"Razer", 
            nombre: "Razer Naga Trinity", 
            tipo:"Gamer", 
            precio:"139000",
            desc: "El mouse de juego te ofrecerá la posibilidad de marcar la diferencia y sacar ventajas en tus partidas. Su conectividad y sensor suave ayudará a que te desplaces rápido por la pantalla. El sistema de detección de movimiento óptico te permitirá mover el cursor de una manera más precisa y sensible que en los sistemas tradicionales. Con sus 19 botones podrás tener mayor control e independencia para ejecutar. Navegá rápidamente por documentos y páginas web gracias su diseño ultra delgado, ergonómico, liviano y conveniente para llevar a donde quieras o viajar.",  
            img: "https://http2.mlstatic.com/D_NQ_NP_672897-MLA32146214449_092019-V.webp",
            stock: "10",
            categoria: "2",  
        },
        {
            id:"9", 
            marca:"Logitech", 
            nombre: "Logitech G Series Hero G502",
            tipo:"Gamer",  
            precio:"6700",
            desc: "El mouse de juego te ofrecerá la posibilidad de marcar la diferencia y sacar ventajas en tus partidas. Su conectividad y sensor suave ayudará a que te desplaces rápido por la pantalla. El sistema de detección de movimiento óptico te permitirá mover el cursor de una manera más precisa y sensible que en los sistemas tradicionales. Con sus 11 botones podrás tener mayor control e independencia para ejecutar. Navegá rápidamente por documentos y páginas web gracias su diseño ultra delgado, ergonómico, liviano y conveniente para llevar a donde quieras o viajar.",  
            img: "https://http2.mlstatic.com/D_NQ_NP_701613-MLA45464844877_042021-V.webp",
            stock: "3",
            categoria: "2", 
        },
        {
            id:"10", 
            marca:"Razer", 
            nombre: "Razer Orochi V2",
            tipo:"Gamer Inalámbrico",  
            precio:"8500",
            desc:"El mouse de juego te ofrecerá la posibilidad de marcar la diferencia y sacar ventajas en tus partidas. Su conectividad y sensor suave ayudará a que te desplaces rápido por la pantalla. El sistema de detección de movimiento óptico te permitirá mover el cursor de una manera más precisa y sensible que en los sistemas tradicionales. Solo debés colocar el receptor en un puerto USB de la computadora y ya podés empezar a usarlo. No hace falta emparejar el mouse ni descargar software para utilizarlo. Gracias a su tecnología Bluetooth tendrás la libertad para crear cuando quieras, donde quieras, en la computadora que elijas, con toda comodidad.",
            img:"https://http2.mlstatic.com/D_NQ_NP_948019-MLA48741007549_012022-V.webp",
            stock: "12",
            categoria: "2", 
        },
];

export default data;